---
# see https://github.com/robvanderleek/create-issue-branch
# A developer that wants to work on issue gives command /cib as a comment on the issue
name: Issue Branch creation

on:
  # The issue.opened event below is only needed for the "immediate" mode.
  # The issue.assigned event below is only needed for the default ("auto") mode.
  issues:
    types: [ assigned ]
    # The issue_comment.created event below is only needed for the ChatOps mode.
    # issue_comment:
    #   types: [ created ]
    # The pull_request events below are only needed for pull-request related features.
    pull_request:
      types: [ opened, closed ]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  create_issue_branch:
    runs-on: ubuntu-latest
    steps:
      - name: ♻️ Processing
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
