---
name: PR Checks

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    name: Lint & Test
    uses: ./.github/workflows/__tests.yml
    secrets: inherit
    with:
      cache-read-only: true
      debug: true

concurrency:
  # один запуск workflow для каждого pr
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true
