---
name: PR Checks

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  test:
    name: Lint & Test
    uses: ./.github/workflows/__tests.yml
    secrets: inherit
    with:
      run-lint: true
      cache-read-only: true
      upload-test-result: true
      upload-coverage: true

concurrency:
  # один запуск workflow для каждого pr
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true
