---
name: Docker Image publication

on:
  release:
    types:
      - published

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  test:
    name: Test
    uses: ./.github/workflows/__tests.yml
    secrets: inherit

  publish:
    needs: [ test ]
    environment: DockerHub
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: init jvm
        uses: sdkman/sdkman-action@main
      - run: source $HOME/.sdkman/bin/sdkman-init.sh && echo "JAVA_HOME=$SDKMAN_DIR/candidates/java/current" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Build & Publish Docker Image
        run: ./gradlew bootBuildImage
        env:
          ORG_GRADLE_PROJECT_version: ${{ github.ref_name }}
          ORG_GRADLE_PROJECT_imageName: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}
          ORG_GRADLE_PROJECT_withLatest: true
          ORG_GRADLE_PROJECT_dockerHubUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          ORG_GRADLE_PROJECT_dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}


concurrency:
  # один запуск для каждой ветки
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
